In [1]:
# 导包
import pandas as pd
import os
os.chdir('E:\python\project\python\pandas')
# os.chdir("/Users/baidengchao/Desktop/code/python/pandas")
ds=pd.read_csv('./data/stock_day.csv')
ds.head(10)

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,22.406,21.955,22.942,40827.52,42736.34,56007.50,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,21.938,21.929,23.022,35119.58,41871.97,56372.85,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,21.446,21.909,23.137,35397.58,39904.78,60149.60,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,21.366,21.923,23.253,33590.21,42935.74,61716.11,0.58
2018-02-13,21.40,21.90,21.48,21.31,30802.45,0.28,1.32,21.342,22.103,23.387,39694.65,45518.14,65161.68,0.77
2018-02-12,20.70,21.40,21.19,20.63,32445.39,0.82,4.03,21.504,22.338,23.533,44645.16,45679.94,68686.33,0.81
2018-02-09,21.20,21.46,20.36,20.19,54304.01,-1.50,-6.86,21.920,22.596,23.645,48624.36,48982.38,70552.47,1.36
2018-02-08,21.79,22.09,21.88,21.75,27068.16,0.09,0.41,22.372,23.009,23.839,44411.98,48612.16,73852.45,0.68
2018-02-07,22.69,23.11,21.80,21.29,53853.25,-0.50,-2.24,22.480,23.258,23.929,52281.28,56315.11,74925.33,1.35

In [2]:
## 逻辑运算符号
ds.head(5).loc[["2018-02-27","2018-02-23","2018-02-22"]]
ds.head(5).iloc[[0,2,3]]
ds.head()[[True,False,True,True,False]]

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,21.938,21.929,23.022,35119.58,41871.97,56372.85,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,21.446,21.909,23.137,35397.58,39904.78,60149.60,0.90

In [3]:
# 需求1: 筛选出ds中, 所有open价格在23以上的数据
ds[ds["open"]>=23]

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-01,23.71,23.86,22.42,22.22,66414.64,-1.30,-5.48,23.646,24.365,24.279,52812.35,80394.43,88480.92,1.66
2018-01-31,23.85,23.98,23.72,23.31,49155.02,-0.11,-0.46,24.036,24.583,24.411,60348.94,80496.48,91666.75,1.23
2018-01-30,23.71,24.08,23.83,23.70,32420.43,0.05,0.21,24.350,24.671,24.365,77485.53,84805.23,92943.35,0.81
2018-01-29,24.40,24.63,23.77,23.72,65469.81,-0.73,-2.98,24.684,24.728,24.294,91842.60,91692.73,93456.22,1.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-05-21,27.50,28.22,28.22,26.50,121190.11,2.57,10.02,24.508,22.725,22.053,117760.48,103865.87,98766.20,4.15
2015-05-20,24.10,25.65,25.65,24.10,164143.16,2.33,9.99,23.292,21.784,21.733,118737.32,98652.00,99743.64,5.62
2015-05-19,23.68,23.69,23.32,22.47,82945.73,0.25,1.08,22.318,21.166,21.536,100396.01,90830.02,97087.92,2.84
2015-04-16,24.63,25.21,22.97,21.94,221070.31,-1.41,-5.78,22.230,19.983,17.825,182172.04,153247.63,124317.19,7.57
2015-04-15,23.45,25.56,24.38,23.40,250311.59,1.14,4.91,21.560,19.315,17.442,174581.78,138001.54,119340.61,8.57

In [4]:
# 需求2: 筛选出ds中, 所有open价格在[23, 24]之间的数据
res=ds[(ds["open"]>=23) & (ds['open']<=24)]

#验证:排序一下看看取得数据是否和结果能对应
res.sort_values("open",ascending=True)

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2017-12-18,23.00,23.49,23.13,22.83,29610.00,0.12,0.52,23.478,22.877,23.617,62395.75,58694.09,60331.46,0.74
2017-06-21,23.00,23.84,23.57,22.90,205097.59,-0.51,-2.12,22.232,20.579,19.268,206391.22,129693.95,82884.05,5.13
2017-07-25,23.07,24.20,23.70,22.64,167489.48,0.67,2.91,23.042,22.759,22.199,137135.54,156145.65,166607.70,4.19
2017-06-27,23.10,23.24,22.20,22.06,288556.75,-1.06,-4.56,23.660,22.519,20.555,327174.26,253323.02,148477.09,7.22
2016-11-07,23.11,23.39,23.06,22.84,44069.47,-0.33,-1.41,23.312,23.609,22.637,84152.81,106671.47,79616.43,1.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-12-23,23.97,24.44,24.11,23.66,70107.29,0.33,1.39,23.836,23.012,22.217,78284.79,69944.93,66730.18,2.40
2017-12-13,23.99,24.38,23.81,23.60,68659.12,-0.15,-0.63,23.082,23.052,24.104,67498.84,64780.47,73475.40,1.72
2018-01-05,24.00,25.40,24.51,23.70,204266.23,-0.56,-2.23,23.420,22.820,23.048,97543.60,76964.50,64853.80,5.11
2017-06-23,24.00,24.47,23.34,23.34,438271.69,-2.59,-9.99,23.884,21.699,20.020,333612.72,206858.19,123274.25,10.97
2015-07-24,24.00,24.55,22.99,22.38,132799.91,-1.15,-4.76,22.404,22.716,24.583,120054.00,135023.38,129589.61,4.55

## 逻辑运算函数

In [5]:
# query(直接写比较表达式即可.)
# 需求: 筛选出df中, 所有open价格在[23, 24]之间的数据
ds.query("open>=23 & open<=24")

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-01,23.71,23.86,22.42,22.22,66414.64,-1.30,-5.48,23.646,24.365,24.279,52812.35,80394.43,88480.92,1.66
2018-01-31,23.85,23.98,23.72,23.31,49155.02,-0.11,-0.46,24.036,24.583,24.411,60348.94,80496.48,91666.75,1.23
2018-01-30,23.71,24.08,23.83,23.70,32420.43,0.05,0.21,24.350,24.671,24.365,77485.53,84805.23,92943.35,0.81
2018-01-16,23.40,24.60,24.40,23.30,101295.42,0.96,4.10,23.908,24.058,23.321,82003.73,101081.47,74590.92,2.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-07-24,24.00,24.55,22.99,22.38,132799.91,-1.15,-4.76,22.404,22.716,24.583,120054.00,135023.38,129589.61,4.55
2015-07-23,23.20,24.26,24.14,23.00,141147.69,1.68,7.48,22.030,22.978,25.000,112668.13,138161.35,127490.18,4.83
2015-06-30,23.82,25.13,25.01,21.44,174521.44,1.19,5.00,25.830,27.929,29.447,140738.14,119712.07,142160.16,5.97
2015-05-19,23.68,23.69,23.32,22.47,82945.73,0.25,1.08,22.318,21.166,21.536,100396.01,90830.02,97087.92,2.84
2015-04-15,23.45,25.56,24.38,23.40,250311.59,1.14,4.91,21.560,19.315,17.442,174581.78,138001.54,119340.61,8.57

In [6]:
# 3. isin([值1, 值2....]) 判断是否是其中的任意1个值
ds
# 需求: 筛选出df中价格为 23.80 或者22.61的数据.
ds.query("open==23.80 or open==22.61")
ds[(ds["open"]==23.80) | (ds["open"]==22.61)]
ds.query("open in [23.80,22.61]")

# 使用isin函数
ds[ds["open"].isin([23.80,22.61])]

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2017-12-12,22.61,24.14,23.98,22.61,125206.36,1.21,5.31,22.732,23.100,24.337,64299.97,63480.44,76113.42,3.13
2017-12-11,22.61,22.94,22.75,22.50,41287.00,0.14,0.62,22.276,23.172,24.605,54992.43,55860.66,82041.76,1.03
2016-11-02,23.80,23.99,23.10,23.00,105628.11,-0.78,-3.27,23.836,23.061,22.391,110733.47,98134.50,78653.50,2.64
2015-12-22,23.80,24.10,23.80,23.50,53460.38,-0.11,-0.46,23.462,22.731,22.204,72633.58,68271.22,66575.31,1.83

## 基本函数

In [7]:
# DataFrame 的描述信息
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 643 entries, 2018-02-27 to 2015-03-02
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   open          643 non-null    float64
 1   high          643 non-null    float64
 2   close         643 non-null    float64
 3   low           643 non-null    float64
 4   volume        643 non-null    float64
 5   price_change  643 non-null    float64
 6   p_change      643 non-null    float64
 7   ma5           643 non-null    float64
 8   ma10          643 non-null    float64
 9   ma20          643 non-null    float64
 10  v_ma5         643 non-null    float64
 11  v_ma10        643 non-null    float64
 12  v_ma20        643 non-null    float64
 13  turnover      643 non-null    float64
dtypes: float64(14)
memory usage: 91.5+ KB

In [8]:
# DataFrame 的统计信息
ds.describe()

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
count,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000
mean,21.272706,21.900513,21.336267,20.771835,99905.519114,0.018802,0.190280,21.302362,21.267656,21.200946,100008.642691,100287.542177,100797.518398,2.936190
std,3.930973,4.077578,3.942806,3.791968,73879.119354,0.898476,4.079698,3.880640,3.813602,3.686186,62761.578326,56759.082060,50101.575639,2.079375
min,12.250000,12.670000,12.360000,12.200000,1158.120000,-3.520000,-10.030000,12.520000,12.520000,12.520000,10804.740000,19130.510000,23311.000000,0.040000
25%,19.000000,19.500000,19.045000,18.525000,48533.210000,-0.390000,-1.850000,18.990000,19.102000,19.275000,55794.985000,59861.955000,64103.675000,1.360000
50%,21.440000,21.970000,21.450000,20.980000,83175.930000,0.050000,0.260000,21.504000,21.623000,21.530000,86133.330000,89234.970000,96291.730000,2.500000
75%,23.400000,24.065000,23.415000,22.850000,127580.055000,0.455000,2.305000,23.318000,23.098500,23.136000,127655.655000,124693.255000,124001.015000,3.915000
max,34.990000,36.350000,35.210000,34.010000,501915.410000,3.030000,10.030000,33.696000,32.186000,29.998000,404443.540000,360028.160000,269280.790000,12.560000

In [11]:

ds.mean() # DataFrame 平均值
ds.std() #  标准差
ds.abs() # 绝对值
ds.max() # 最大值 
ds["open"].min() #最小值
ds.var() # 方差

open            1.545255e+01
high            1.662665e+01
close           1.554572e+01
low             1.437902e+01
volume          5.458124e+09
price_change    8.072595e-01
p_change        1.664394e+01
ma5             1.505937e+01
ma10            1.454356e+01
ma20            1.358797e+01
v_ma5           3.939016e+09
v_ma10          3.221593e+09
v_ma20          2.510168e+09
turnover        4.323800e+00
dtype: float64

In [14]:
ds.open.idxmax() # 最大值的索引
ds.high.idxmin() # 最小值的索引

'2015-03-02'

In [19]:
ds.head().cumsum() #列数值累加
ds.head().cumsum(axis=1) #行数值累加

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,49.41,73.57,97.10,95675.13,95675.76,95678.44,95701.382,95723.524,95746.399,149529.039,196267.689,251843.799,251846.189
2018-02-26,22.80,46.58,70.11,92.91,61078.02,61078.71,61081.73,61104.136,61126.091,61149.033,101976.553,144712.893,200720.393,200721.923
2018-02-23,22.88,46.25,69.07,91.78,53005.79,53006.33,53008.75,53030.688,53052.617,53075.639,88195.219,130067.189,186440.039,186441.359
2018-02-22,22.25,45.01,67.29,89.31,36194.32,36194.68,36196.32,36217.766,36239.675,36262.812,71660.392,111565.172,171714.772,171715.672
2018-02-14,21.49,43.48,65.40,86.88,23417.92,23418.36,23420.41,23441.776,23463.699,23486.952,57077.162,100012.902,161729.012,161729.592

In [29]:
# apply 自定义函数
ds["open"].apply(lambda col:col+1) # apply 里面接受一个自定义函数,
ds["high"].head().apply(lambda row:row*2)

2018-02-27    51.76
2018-02-26    47.56
2018-02-23    46.74
2018-02-22    45.52
2018-02-14    43.98
Name: high, dtype: float64