# pandas 数据合并和分组聚合

In [2]:
import pandas as pd
import numpy as np
import os
os.getcwd()
os.chdir("/Users/baidengchao/Desktop/code/python/pandas")

In [17]:
ds=pd.read_csv('./data/uniqlo.csv')
ds.head(10)

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
0,658,深圳,线下,Female,25-29,Weekday,当季新品,4,796.0,4,4,59
1,146,杭州,线下,Female,25-29,Weekday,运动,1,149.0,1,1,49
2,70,深圳,线下,Male,>=60,Weekday,T恤,2,178.0,2,2,49
3,658,深圳,线下,Female,25-29,Weekday,T恤,1,59.0,1,1,49
4,229,深圳,线下,Male,20-24,Weekend,袜子,2,65.0,2,3,9
5,28,武汉,线上,Female,35-39,Weekend,T恤,1,97.0,1,1,49
6,649,杭州,线下,Female,25-29,Weekend,短裤,1,33.0,1,1,19
7,520,杭州,线下,Male,>=60,Weekend,T恤,2,158.0,2,2,49
8,649,杭州,线下,Female,30-34,Weekend,牛仔裤,3,157.0,3,3,69
9,21,北京,线下,Female,45-49,Weekend,毛衣,1,199.0,1,1,99

In [31]:
# 单个元素分组
ds.groupby("city").get_group("北京")
# 多个元素分组,查看页面数据
ds.groupby(["city","channel"]).get_group(("北京","线下"))

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
9,21,北京,线下,Female,45-49,Weekend,毛衣,1,199.00,1,1,99
168,21,北京,线下,Female,35-39,Weekday,毛衣,3,447.00,3,3,99
175,21,北京,线下,Female,45-49,Weekend,配件,1,149.00,1,1,29
263,21,北京,线下,Male,20-24,Weekday,T恤,1,55.33,1,1,49
289,21,北京,线下,Female,35-39,Weekend,牛仔裤,1,199.00,1,1,69
...,...,...,...,...,...,...,...,...,...,...,...,...
22037,21,北京,线下,Female,20-24,Weekday,T恤,7,493.00,7,7,49
22110,21,北京,线下,Male,50-54,Weekend,当季新品,1,79.00,1,1,59
22192,21,北京,线下,Female,20-24,Weekday,T恤,7,693.00,7,7,49
22273,21,北京,线下,Female,20-24,Weekday,当季新品,2,288.00,2,2,59
22280,21,北京,线下,Female,35-39,Weekend,T恤,1,59.00,1,1,49