In [ ]:
# 导包
import pandas as pd
import os
os.chdir('E:\python\project\python\pandas')
ds=pd.read_csv('./data/stock_day.csv')
ds.head(10)

In [ ]:
## 逻辑运算符号
ds.head(5).loc[["2018-02-27","2018-02-23","2018-02-22"]]
ds.head(5).iloc[[0,2,3]]
ds.head()[[True,False,True,True,False]]

In [ ]:
# 需求1: 筛选出ds中, 所有open价格在23以上的数据
ds[ds["open"]>=23]

In [ ]:
# 需求2: 筛选出ds中, 所有open价格在[23, 24]之间的数据
res=ds[(ds["open"]>=23) & (ds['open']<=24)]

#验证:排序一下看看取得数据是否和结果能对应
res.sort_values("open",ascending=True)

## 逻辑运算函数

In [30]:
# query(直接写比较表达式即可.)
# 需求: 筛选出df中, 所有open价格在[23, 24]之间的数据
ds.query("open>=23 & open<=24")

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-01,23.71,23.86,22.42,22.22,66414.64,-1.30,-5.48,23.646,24.365,24.279,52812.35,80394.43,88480.92,1.66
2018-01-31,23.85,23.98,23.72,23.31,49155.02,-0.11,-0.46,24.036,24.583,24.411,60348.94,80496.48,91666.75,1.23
2018-01-30,23.71,24.08,23.83,23.70,32420.43,0.05,0.21,24.350,24.671,24.365,77485.53,84805.23,92943.35,0.81
2018-01-16,23.40,24.60,24.40,23.30,101295.42,0.96,4.10,23.908,24.058,23.321,82003.73,101081.47,74590.92,2.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-07-24,24.00,24.55,22.99,22.38,132799.91,-1.15,-4.76,22.404,22.716,24.583,120054.00,135023.38,129589.61,4.55
2015-07-23,23.20,24.26,24.14,23.00,141147.69,1.68,7.48,22.030,22.978,25.000,112668.13,138161.35,127490.18,4.83
2015-06-30,23.82,25.13,25.01,21.44,174521.44,1.19,5.00,25.830,27.929,29.447,140738.14,119712.07,142160.16,5.97
2015-05-19,23.68,23.69,23.32,22.47,82945.73,0.25,1.08,22.318,21.166,21.536,100396.01,90830.02,97087.92,2.84
2015-04-15,23.45,25.56,24.38,23.40,250311.59,1.14,4.91,21.560,19.315,17.442,174581.78,138001.54,119340.61,8.57

In [45]:
# 3. isin([值1, 值2....]) 判断是否是其中的任意1个值
ds
# 需求: 筛选出df中价格为 23.80 或者22.61的数据.
ds.query("open==23.80 or open==22.61")
ds[(ds["open"]==23.80) | (ds["open"]==22.61)]
ds.query("open in [23.80,22.61]")

# 使用isin函数
ds[ds["open"].isin([23.80,22.61])]

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2017-12-12,22.61,24.14,23.98,22.61,125206.36,1.21,5.31,22.732,23.100,24.337,64299.97,63480.44,76113.42,3.13
2017-12-11,22.61,22.94,22.75,22.50,41287.00,0.14,0.62,22.276,23.172,24.605,54992.43,55860.66,82041.76,1.03
2016-11-02,23.80,23.99,23.10,23.00,105628.11,-0.78,-3.27,23.836,23.061,22.391,110733.47,98134.50,78653.50,2.64
2015-12-22,23.80,24.10,23.80,23.50,53460.38,-0.11,-0.46,23.462,22.731,22.204,72633.58,68271.22,66575.31,1.83