# pandas 数据分组及分组聚合

In [2]:
import pandas as pd
import numpy as np 
import os
os.getcwd()
os.chdir("E:\python\project\python\pandas")

In [11]:
# 准备数据.
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                        'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                        'key2': ['K0', 'K0', 'K0', 'K0'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']})
df3 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                        'key2': ['K0', 'K0', 'K0', 'K0'],
                        'E': ['E0', 'E1', 'E2', 'E3'],
                        'F': ['F0', 'F1', 'F2', 'F3']},index=[10, 11, 12, 13])

## 数据合并concat

In [12]:
# concat 数据合并--默认纵向合并 axis=0,axis横向合并可设置值为1
ds_col=pd.concat([left,right],axis=0)
# axis=1 横向合并,缺失的数据用NaN填充
ds_row=pd.concat([left,right],axis=1)
ds_row

  key1 key2   A   B key1 key2   C   D
0   K0   K0  A0  B0   K0   K0  C0  D0
1   K0   K1  A1  B1   K1   K0  C1  D1
2   K1   K0  A2  B2   K1   K0  C2  D2
3   K2   K1  A3  B3   K2   K0  C3  D3

In [17]:
ds1=pd.concat([left,df3])
ds1
ds2=pd.concat([left,df3],axis=1)
ds2

   key1 key2    A    B key1 key2    E    F
0    K0   K0   A0   B0  NaN  NaN  NaN  NaN
1    K0   K1   A1   B1  NaN  NaN  NaN  NaN
2    K1   K0   A2   B2  NaN  NaN  NaN  NaN
3    K2   K1   A3   B3  NaN  NaN  NaN  NaN
10  NaN  NaN  NaN  NaN   K0   K0   E0   F0
11  NaN  NaN  NaN  NaN   K1   K0   E1   F1
12  NaN  NaN  NaN  NaN   K1   K0   E2   F2
13  NaN  NaN  NaN  NaN   K2   K0   E3   F3

# 分组聚合

In [19]:
# 获取数据
ds=pd.read_csv('./data/uniqlo.csv')
ds

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
0,658,深圳,线下,Female,25-29,Weekday,当季新品,4,796.0,4,4,59
1,146,杭州,线下,Female,25-29,Weekday,运动,1,149.0,1,1,49
2,70,深圳,线下,Male,>=60,Weekday,T恤,2,178.0,2,2,49
3,658,深圳,线下,Female,25-29,Weekday,T恤,1,59.0,1,1,49
4,229,深圳,线下,Male,20-24,Weekend,袜子,2,65.0,2,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...
22288,146,杭州,线下,Female,30-34,Weekday,短裤,1,80.0,1,2,19
22289,430,成都,线下,Female,25-29,Weekend,T恤,1,79.0,1,1,49
22290,449,武汉,线下,Female,35-39,Weekday,T恤,1,158.0,1,2,49
22291,758,杭州,线下,Female,20-24,Weekday,袜子,1,26.0,1,1,9
22292,616,成都,线下,Male,30-34,Weekday,当季新品,1,79.0,1,1,59

In [26]:
# 使用groupby函数进行分组,得到的数据类型为DataFrameGroupBy 类型
# 单列分组
by_city=ds.groupby("city")
# 通过获取分组的信息来查看具体数据
by_city.get_group("北京").head() # 获取到所有属于北京的数据

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
9,21,北京,线下,Female,45-49,Weekend,毛衣,1,199.00,1,1,99
168,21,北京,线下,Female,35-39,Weekday,毛衣,3,447.00,3,3,99
175,21,北京,线下,Female,45-49,Weekend,配件,1,149.00,1,1,29
263,21,北京,线下,Male,20-24,Weekday,T恤,1,55.33,1,1,49
289,21,北京,线下,Female,35-39,Weekend,牛仔裤,1,199.00,1,1,69

In [33]:
# 基于多列分组
multiple_group=ds.groupby(["city","channel"])
multiple_group.get_group(('北京',"线下")).head(20)
# 获取第一条或者最后一条数据
multiple_group.first()
multiple_group.last()

              store_id gender_group age_group  wkd_ind product  customer  \
city channel
上海   线上            207       Female     20-24  Weekday    当季新品         1
     线下            335       Female     35-39  Weekend      运动         3
北京   线下             21       Female     35-39  Weekend      T恤         1
南京   线下             19       Female     45-49  Weekend      短裤         1
广州   线上            182       Female     25-29  Weekday    当季新品         3
     线下            399         Male     30-34  Weekday      T恤         1
成都   线下            616         Male     30-34  Weekday    当季新品         1
杭州   线下            758       Female     20-24  Weekday      袜子         1
武汉   线上             52       Female     40-44  Weekend      T恤         1
     线下            449       Female     35-39  Weekday      T恤         1
深圳   线下            738       Female     45-49  Weekday      配件         1
西安   线上            137       Female     20-24  Weekday      T恤         1
     线下            429         Male     25-29  Weekday      T恤         1
重庆   线上             68       Female     40-44  Weekday    当季新品         2
     线下            208       Female     45-49  Weekend      T恤         1

              revenue  order  quant  unit_cost
city channel
上海   线上         55.32      1      1         59
     线下        447.00      3      3         49
北京   线下         59.00      1      1         49
南京   线下         39.00      1      1         19
广州   线上        297.00      3      3         59
     线下         79.00      1      1         49
成都   线下         79.00      1      1         59
杭州   线下         26.00      1      1          9
武汉   线上         99.00      1      1         49
     线下        158.00      1      2         49
深圳   线下        158.00      1      2         29
西安   线上         59.00      1      1         49
     线下         99.00      1      1         49
重庆   线上        156.00      2      2         59
     线下         79.00      1      1         49

In [35]:
# 格式: ds.groupby(['分组字段1', '字段2'...]).agg({'列名1':'聚合函数名', '列名2':'聚合函数名'...})
ds.groupby(["revenue","order"]).agg({"customer":"sum",'unit_cost':"mean"})

                 customer  unit_cost
revenue   order
-0.66     1             1  49.000000
 0.00     1            30  43.666667
 10.00    1            16  12.750000
 13.00    1             1  99.000000
 13.26    1             1   9.000000
...                   ...        ...
 6636.00  4             1  49.000000
 7919.00  48           44  59.000000
 8836.00  54           45  59.000000
 10498.28 65           58  59.000000
 12538.00 45           42  59.000000

[2078 rows x 2 columns]

In [ ]:
# 格式: ds.pivot_table(index='行索引', columns='列', values='值', aggfunc='聚合函数名')\
# ds.pivot_table(index="city",columns='revenue')